[package]
name = "adventofcode-2020"
version = "0.1.0"
authors = ["Lars-Olof Moilanen <lo@jpro.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_tool = "1.0.3"
